/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.r02_04_02.lab.polb_mt004100ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.model.MessagePartBean;



/**
 * <p>Isolate Participation</p>
 * 
 * <p><p>Associates the isolate specimen and specimen material 
 * (identification of the microorganism) with the grouper 
 * specimen cluster (object).</p></p>
 */
@Hl7PartTypeMapping({"POLB_MT004100CA.Specimen2"})
public class IsolateParticipationBean extends MessagePartBean {

    private static final long serialVersionUID = 20110407L;
    private IsolateBean isolate;


    @Hl7XmlMapping({"isolate"})
    public IsolateBean getIsolate() {
        return this.isolate;
    }
    public void setIsolate(IsolateBean isolate) {
        this.isolate = isolate;
    }

}
