/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.pr.prpm_mt301010ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;



@Hl7PartTypeMapping({"PRPM_MT301010CA.Choice"})
public interface ChoiceBean {

}
