/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.pharmacy.porx_mt060190ca;

import ca.infoway.messagebuilder.Code;
import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.CD;
import ca.infoway.messagebuilder.datatype.ST;
import ca.infoway.messagebuilder.datatype.impl.CDImpl;
import ca.infoway.messagebuilder.datatype.impl.STImpl;
import ca.infoway.messagebuilder.model.MessagePartBean;



@Hl7PartTypeMapping({"PORX_MT060190CA.AdministrationInstructions"})
public class AdministrationInstructionsBean extends MessagePartBean {

    private static final long serialVersionUID = 20100603L;
    private CD medicationType = new CDImpl();
    private ST renderedDosageInstruction = new STImpl();

    @Hl7XmlMapping({"code"})
    public Code getMedicationType() {
        return (Code) this.medicationType.getValue();
    }
    public void setMedicationType(Code medicationType) {
        this.medicationType.setValue(medicationType);
    }

    @Hl7XmlMapping({"text"})
    public String getRenderedDosageInstruction() {
        return this.renderedDosageInstruction.getValue();
    }
    public void setRenderedDosageInstruction(String renderedDosageInstruction) {
        this.renderedDosageInstruction.setValue(renderedDosageInstruction);
    }

}
