/**
 * Copyright 2013 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 15:47:15 -0400 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.nb_drug.interaction;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.model.InteractionBean;
import ca.infoway.messagebuilder.model.nb_drug.common.mcai_mt700210nb.TriggerEventBean;
import ca.infoway.messagebuilder.model.nb_drug.common.mcci_mt000100nb.HL7MessageBean;
import ca.infoway.messagebuilder.model.nb_drug.pharmacy.porx_mt990010nb.ReferencedRecordBean;



/**
 * <p>Business Name: COMT_IN600001NB: Retract action request</p>
 * 
 * <p>Seeks to have an identified ControlAct nullified, 
 * essentially reversing the record of the event.</p>
 * 
 * <p>Generally, for most actions, specific actions may be 
 * retracted when no additional activity has occurred and if 
 * the request is within a specific timeframe from the original 
 * action. The timeframe depends on the action itself and will 
 * be subject to jurisdictional rules. See &ldquo;Appendix B 
 * &ndash; Retract Action Rules&rdquo; of the &quot;Drug 
 * Information System - Phase 2 Vendor Implementation Guide - 
 * Volume C - Messaging Specifications&quot; document for more 
 * information.</p>
 * 
 * <p>Message: MCCI_MT000100NB.Message</p>
 * 
 * <p>Control Act: MCAI_MT700210NB.ControlActEvent</p>
 * 
 * <p>--> Payload: PORX_MT990010NB.ActEvent</p>
 */
@Hl7PartTypeMapping({"COMT_IN600001NB"})
public class RetractActionRequestBean extends HL7MessageBean<TriggerEventBean<ReferencedRecordBean>> implements InteractionBean {

    private static final long serialVersionUID = 20150901L;

}
