/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.iehr.repc_mt100002ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.TS;
import ca.infoway.messagebuilder.datatype.impl.TSImpl;
import ca.infoway.messagebuilder.model.MessagePartBean;
import ca.infoway.messagebuilder.model.common.coct_mt090107ca.ProviderBean;
import java.util.Date;



/**
 * <p>*b:recorded by</p>
 * 
 * <p>Identifies the provider responsible for the recording the 
 * patient measurement.</p>
 * 
 * <p>Only needs to be specified if the author of the 
 * annotation differs from the prescriber.</p>
 * 
 * <p>Allows tracking of who made the patient observation. This 
 * attribute is mandatory because the provider responsible for 
 * the observation must be known.</p>
 * 
 * <p>Annotation.requestingProvider</p>
 * 
 * <p>ZPB3.18 (id.root)</p>
 * 
 * <p>ZPB3.19 (id.extension)</p>
 * 
 * <p>ZPB3.15</p>
 */
@Hl7PartTypeMapping({"REPC_MT100002CA.Author3"})
public class RecordedByBean extends MessagePartBean {

    private static final long serialVersionUID = 20100614L;
    private TS recordingDatetime = new TSImpl();
    private ProviderBean assignedPerson;

    @Hl7XmlMapping({"time"})
    public Date getRecordingDatetime() {
        return this.recordingDatetime.getValue();
    }
    public void setRecordingDatetime(Date recordingDatetime) {
        this.recordingDatetime.setValue(recordingDatetime);
    }

    @Hl7XmlMapping({"assignedPerson"})
    public ProviderBean getAssignedPerson() {
        return this.assignedPerson;
    }
    public void setAssignedPerson(ProviderBean assignedPerson) {
        this.assignedPerson = assignedPerson;
    }

}
