/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.interaction;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.model.InteractionBean;
import ca.infoway.messagebuilder.model.common.mcci_mt002200ca.HL7MessageBean;



/**
 * <p>Communication level acknowledgement indicating exception 
 * as to why message payload not returned by poll request that 
 * has been received. Note: This interaction is invoked, where 
 * appropriate, as a receiver responsibility. 
 */
@Hl7PartTypeMapping({"MCCI_IN100005CA"})
public class ExceptionAckInResponseToPollRequestBean extends HL7MessageBean implements InteractionBean {


}
