/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.r02_04_02.common.coct_mt110200ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;



@Hl7PartTypeMapping({"COCT_MT110200CA.PayeeChoice"})
public interface PayeeChoice {

    public PayeeRelationshipRoleBean getAsRole();
    public void setAsRole(PayeeRelationshipRoleBean asRole);

}
