/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy$
 * Last modified: $LastChangedDate$
 * Revision:      $LastChangedRevision$
 */

/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.common.coct_mt490000ca;

import ca.infoway.messagebuilder.Code;
import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.CV;
import ca.infoway.messagebuilder.datatype.IVL;
import ca.infoway.messagebuilder.datatype.PQ;
import ca.infoway.messagebuilder.datatype.ST;
import ca.infoway.messagebuilder.datatype.TEL;
import ca.infoway.messagebuilder.datatype.TS;
import ca.infoway.messagebuilder.datatype.impl.CVImpl;
import ca.infoway.messagebuilder.datatype.impl.IVLImpl;
import ca.infoway.messagebuilder.datatype.impl.PQImpl;
import ca.infoway.messagebuilder.datatype.impl.STImpl;
import ca.infoway.messagebuilder.datatype.impl.TELImpl;
import ca.infoway.messagebuilder.datatype.impl.TSImpl;
import ca.infoway.messagebuilder.datatype.lang.Interval;
import ca.infoway.messagebuilder.datatype.lang.PhysicalQuantity;
import ca.infoway.messagebuilder.datatype.lang.TelecommunicationAddress;
import ca.infoway.messagebuilder.model.MessagePartBean;
import java.util.Date;



/**
 * <p>Manufactured Material Kind 
 * 
 * <p>Type of Product 
 */
@Hl7PartTypeMapping({"COCT_MT490000CA.ManufacturedMaterialKind"})
public class ManufacturedMaterialKindBean extends MessagePartBean {

    private CV<Code> manufacturedMaterialCode = new CVImpl<Code>();
    private ST packageDescription = new STImpl();
    private PQ packageQuantity = new PQImpl();
    private ManufacturedMaterialKindBean contentPackagedProductContainedManufacturedMaterialKind;
    private IVL<TS, Interval<Date>> asWarrantorEffectiveTime = new IVLImpl<TS, Interval<Date>>();
    private ST warrantorOrganisationName = new STImpl();
    private TEL warrantorOrganisationTelecom = new TELImpl();

    @Hl7XmlMapping({"code"})
    public Code getManufacturedMaterialCode() {
        return this.manufacturedMaterialCode.getValue();
    }
    public void setManufacturedMaterialCode(Code manufacturedMaterialCode) {
        this.manufacturedMaterialCode.setValue(manufacturedMaterialCode);
    }

    @Hl7XmlMapping({"desc"})
    public java.lang.String getPackageDescription() {
        return this.packageDescription.getValue();
    }
    public void setPackageDescription(java.lang.String packageDescription) {
        this.packageDescription.setValue(packageDescription);
    }

    @Hl7XmlMapping({"contentPackagedProduct/quantity"})
    public PhysicalQuantity getPackageQuantity() {
        return this.packageQuantity.getValue();
    }
    public void setPackageQuantity(PhysicalQuantity packageQuantity) {
        this.packageQuantity.setValue(packageQuantity);
    }

    @Hl7XmlMapping({"contentPackagedProduct/containedManufacturedMaterialKind"})
    public ManufacturedMaterialKindBean getContentPackagedProductContainedManufacturedMaterialKind() {
        return this.contentPackagedProductContainedManufacturedMaterialKind;
    }
    public void setContentPackagedProductContainedManufacturedMaterialKind(ManufacturedMaterialKindBean contentPackagedProductContainedManufacturedMaterialKind) {
        this.contentPackagedProductContainedManufacturedMaterialKind = contentPackagedProductContainedManufacturedMaterialKind;
    }

    @Hl7XmlMapping({"asWarrantor/effectiveTime"})
    public Interval<Date> getAsWarrantorEffectiveTime() {
        return this.asWarrantorEffectiveTime.getValue();
    }
    public void setAsWarrantorEffectiveTime(Interval<Date> asWarrantorEffectiveTime) {
        this.asWarrantorEffectiveTime.setValue(asWarrantorEffectiveTime);
    }

    @Hl7XmlMapping({"asWarrantor/warrantingWarrantorOrganization/name"})
    public java.lang.String getWarrantorOrganisationName() {
        return this.warrantorOrganisationName.getValue();
    }
    public void setWarrantorOrganisationName(java.lang.String warrantorOrganisationName) {
        this.warrantorOrganisationName.setValue(warrantorOrganisationName);
    }

    @Hl7XmlMapping({"asWarrantor/warrantingWarrantorOrganization/telecom"})
    public TelecommunicationAddress getWarrantorOrganisationTelecom() {
        return this.warrantorOrganisationTelecom.getValue();
    }
    public void setWarrantorOrganisationTelecom(TelecommunicationAddress warrantorOrganisationTelecom) {
        this.warrantorOrganisationTelecom.setValue(warrantorOrganisationTelecom);
    }

}
