package ca.infoway.messagebuilder.xml;

public enum DifferenceType {
	
	INTERACTION_SUPER_TYPE_NAME,
	ARGUMENT_MISSING,
	ARGUMENT_NAME,
	ARGUMENT_TEMPLATE_PARAMETER_NAME,
	ARGUMENT_TRAVERSAL_NAME,
	PACKAGE_LOCATION_ROOT_TYPE,
	MESSAGE_PART_ABSTRACT,
	RELATIONSHIP_TYPE,
	CHOICE_RELATIONSHIP_MISSING,
	CHOICE_RELATIONSHIP_TYPE,
	RELATIONSHIP_ONLY_ONE_HAS_DOMAIN_TYPE,
	RELATIONSHIP_DOMAIN_TYPES_INCOMPATIBLE,
	RELATIONSHIP_ONE_OR_BOTH_DOMAIN_TYPES_NOT_IN_SYSTEM,
	RELATIONSHIP_TEMPLATE_PARAMETER_NAME
	;
	
}
