/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.ccda_r1_1.pocd_mt000040;

import ca.infoway.messagebuilder.Code;
import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.BL;
import ca.infoway.messagebuilder.datatype.CS_R2;
import ca.infoway.messagebuilder.datatype.II;
import ca.infoway.messagebuilder.datatype.LIST;
import ca.infoway.messagebuilder.datatype.impl.BLImpl;
import ca.infoway.messagebuilder.datatype.impl.CS_R2Impl;
import ca.infoway.messagebuilder.datatype.impl.IIImpl;
import ca.infoway.messagebuilder.datatype.impl.LISTImpl;
import ca.infoway.messagebuilder.datatype.lang.CodedTypeR2;
import ca.infoway.messagebuilder.datatype.lang.Identifier;
import ca.infoway.messagebuilder.model.MessagePartBean;
import ca.infoway.messagebuilder.model.ccda_r1_1.domainvalue.x_ActRelationshipExternalReference;
import java.util.List;



@Hl7PartTypeMapping({"POCD_MT000040.Reference"})
public class ReferenceBean extends MessagePartBean implements ca.infoway.messagebuilder.model.ccda_r1_1.advancedirectiveobservation.ReferenceChoice {

    private static final long serialVersionUID = 20150206L;
    private CS_R2 typeCode = new CS_R2Impl();
    private LIST<CS_R2, CodedTypeR2<? extends Code>> realmCode = new LISTImpl<CS_R2, CodedTypeR2<? extends Code>>(CS_R2Impl.class);
    private II typeId = new IIImpl();
    private LIST<II, Identifier> templateId = new LISTImpl<II, Identifier>(IIImpl.class);
    private BL seperatableInd = new BLImpl();
    private ReferenceChoice referenceChoice;


    /**
     * <p>Relationship: POCD_MT000040.Reference.typeCode</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     */
    @Hl7XmlMapping({"typeCode"})
    public CodedTypeR2<x_ActRelationshipExternalReference> getTypeCode() {
        return (CodedTypeR2<x_ActRelationshipExternalReference>) this.typeCode.getValue();
    }

    /**
     * <p>Relationship: POCD_MT000040.Reference.typeCode</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     */
    public void setTypeCode(CodedTypeR2<x_ActRelationshipExternalReference> typeCode) {
        this.typeCode.setValue(typeCode);
    }


    /**
     * <p>Relationship: POCD_MT000040.Reference.realmCode</p>
     * 
     * <p>Conformance/Cardinality: OPTIONAL (0-*)</p>
     */
    @Hl7XmlMapping({"realmCode"})
    public List<CodedTypeR2<Code>> getRealmCode() {
        return this.realmCode.rawList(CodedTypeR2.class);
    }


    /**
     * <p>Relationship: POCD_MT000040.Reference.typeId</p>
     * 
     * <p>Conformance/Cardinality: OPTIONAL (0-1)</p>
     */
    @Hl7XmlMapping({"typeId"})
    public Identifier getTypeId() {
        return this.typeId.getValue();
    }

    /**
     * <p>Relationship: POCD_MT000040.Reference.typeId</p>
     * 
     * <p>Conformance/Cardinality: OPTIONAL (0-1)</p>
     */
    public void setTypeId(Identifier typeId) {
        this.typeId.setValue(typeId);
    }


    /**
     * <p>Relationship: POCD_MT000040.Reference.templateId</p>
     * 
     * <p>Conformance/Cardinality: OPTIONAL (0-*)</p>
     */
    @Hl7XmlMapping({"templateId"})
    public List<Identifier> getTemplateId() {
        return this.templateId.rawList();
    }


    /**
     * <p>Relationship: POCD_MT000040.Reference.seperatableInd</p>
     * 
     * <p>Conformance/Cardinality: OPTIONAL (0-1)</p>
     */
    @Hl7XmlMapping({"seperatableInd"})
    public Boolean getSeperatableInd() {
        return this.seperatableInd.getValue();
    }

    /**
     * <p>Relationship: POCD_MT000040.Reference.seperatableInd</p>
     * 
     * <p>Conformance/Cardinality: OPTIONAL (0-1)</p>
     */
    public void setSeperatableInd(Boolean seperatableInd) {
        this.seperatableInd.setValue(seperatableInd);
    }


    /**
     * <p>Relationship: POCD_MT000040.Reference.referenceChoice</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     */
    @Hl7XmlMapping({"referenceChoice"})
    public ReferenceChoice getReferenceChoice() {
        return this.referenceChoice;
    }

    /**
     * <p>Relationship: POCD_MT000040.Reference.referenceChoice</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     */
    public void setReferenceChoice(ReferenceChoice referenceChoice) {
        this.referenceChoice = referenceChoice;
    }

    public ExternalActBean getReferenceChoiceAsExternalAct() {
        return this.referenceChoice instanceof ExternalActBean ? (ExternalActBean) this.referenceChoice : null;
    }
    public boolean hasReferenceChoiceAsExternalAct() {
        return (this.referenceChoice instanceof ExternalActBean);
    }

    public ExternalObservationBean getReferenceChoiceAsExternalObservation() {
        return this.referenceChoice instanceof ExternalObservationBean ? (ExternalObservationBean) this.referenceChoice : null;
    }
    public boolean hasReferenceChoiceAsExternalObservation() {
        return (this.referenceChoice instanceof ExternalObservationBean);
    }

    public ExternalProcedureBean getReferenceChoiceAsExternalProcedure() {
        return this.referenceChoice instanceof ExternalProcedureBean ? (ExternalProcedureBean) this.referenceChoice : null;
    }
    public boolean hasReferenceChoiceAsExternalProcedure() {
        return (this.referenceChoice instanceof ExternalProcedureBean);
    }

    public ExternalDocumentBean getReferenceChoiceAsExternalDocument() {
        return this.referenceChoice instanceof ExternalDocumentBean ? (ExternalDocumentBean) this.referenceChoice : null;
    }
    public boolean hasReferenceChoiceAsExternalDocument() {
        return (this.referenceChoice instanceof ExternalDocumentBean);
    }

}
