/**
 * Copyright 2011 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy$
 * Last modified: $LastChangedDate$
 * Revision:      $LastChangedRevision$
 */

/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.pcs_mr2009_r02_04_02.common.coct_mt300000ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.II;
import ca.infoway.messagebuilder.datatype.impl.IIImpl;
import ca.infoway.messagebuilder.datatype.lang.Identifier;
import ca.infoway.messagebuilder.model.MessagePartBean;



/**
 * <p>Playing Prescribe Person</p>
 * 
 * <p><p>ID cannot be mandatory as it may not be present on a 
 * pre-determination</p></p>
 */
@Hl7PartTypeMapping({"COCT_MT300000CA.PresriberRole"})
public class PlayingPrescribePersonBean extends MessagePartBean {

    private static final long serialVersionUID = 20111117L;
    private II id = new IIImpl();
    private PersonPrescribingBean playingPrescriberPerson;


    /**
     * <p>Prescriber ID</p>
     * 
     * <p><p>Prescriber ID</p></p>
     * 
     * <p><p>This is mandatory for Invoices and required with 
     * nullFlavor for Pre-Determinations.</p></p>
     */
    @Hl7XmlMapping({"id"})
    public Identifier getId() {
        return this.id.getValue();
    }
    public void setId(Identifier id) {
        this.id.setValue(id);
    }


    @Hl7XmlMapping({"playingPrescriberPerson"})
    public PersonPrescribingBean getPlayingPrescriberPerson() {
        return this.playingPrescriberPerson;
    }
    public void setPlayingPrescriberPerson(PersonPrescribingBean playingPrescriberPerson) {
        this.playingPrescriberPerson = playingPrescriberPerson;
    }

}
