/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.common.coct_mt080100ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;



@Hl7PartTypeMapping({"COCT_MT080100CA.PerformerChoice"})
public interface PerformerChoice {

}
