/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.r02_04_02.claims.ficr_mt490102ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.model.MessagePartBean;
import ca.infoway.messagebuilder.model.r02_04_02.merged.ClinicalDeviceBean;



@Hl7PartTypeMapping({"FICR_MT490102CA.DevicePassThru"})
public class DevicePassThruBean extends MessagePartBean implements ca.infoway.messagebuilder.model.r02_04_02.claims.merged.SpecialAuthorizationChoice {

    private static final long serialVersionUID = 20110407L;
    private ClinicalDeviceBean directTargetManufacturedProductManufacturedClinicalDevice;


    @Hl7XmlMapping({"directTarget/manufacturedProduct/manufacturedClinicalDevice"})
    public ClinicalDeviceBean getDirectTargetManufacturedProductManufacturedClinicalDevice() {
        return this.directTargetManufacturedProductManufacturedClinicalDevice;
    }
    public void setDirectTargetManufacturedProductManufacturedClinicalDevice(ClinicalDeviceBean directTargetManufacturedProductManufacturedClinicalDevice) {
        this.directTargetManufacturedProductManufacturedClinicalDevice = directTargetManufacturedProductManufacturedClinicalDevice;
    }

}
