/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 15:47:15 -0400 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.pcs_mr2009_r02_04_03.cr.merged;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.CV;
import ca.infoway.messagebuilder.datatype.II;
import ca.infoway.messagebuilder.datatype.ST;
import ca.infoway.messagebuilder.datatype.impl.CVImpl;
import ca.infoway.messagebuilder.datatype.impl.IIImpl;
import ca.infoway.messagebuilder.datatype.impl.STImpl;
import ca.infoway.messagebuilder.datatype.lang.Identifier;
import ca.infoway.messagebuilder.model.MessagePartBean;
import ca.infoway.messagebuilder.model.pcs_mr2009_r02_04_03.domainvalue.OtherIdentifiersRoleType;



/**
 * <p>OtherIDsNonHealthcareIdentifiers</p>
 * 
 * <p>PRPA_MT101104CA.OtherIDs: Other IDs Non Healthcare 
 * Identifiers</p>
 * 
 * <p>Identifiers used for the focal person by other 
 * organizations are sent in the OtherIDs class. The other 
 * organization can be sent in the E_Organization Entity 
 * Class</p>
 * 
 * <p>Provides the ability to capture additional client 
 * identifiers that are not healthcare specific</p>
 * 
 * <p>PRPA_MT101002CA.OtherIDs: Other IDs Non Healthcare 
 * Identifiers</p>
 * 
 * <p>Identifiers used for the focal person by other 
 * organizations are sent in the OtherIDs class. The other 
 * organization can be sent in the E_Organization Entity 
 * Class</p>
 * 
 * <p>Provides the ability to capture additional client 
 * identifiers that are not healthcare specific</p>
 * 
 * <p>PRPA_MT101106CA.OtherIDs: Other IDs Non Healthcare 
 * Identifiers</p>
 * 
 * <p>Identifiers used for the focal person by other 
 * organizations are sent in the OtherIDs class. The other 
 * organization can be sent in the E_Organization Entity 
 * Class</p>
 * 
 * <p>Provides the ability to capture additional client 
 * identifiers that are not healthcare specific</p>
 * 
 * <p>PRPA_MT101102CA.OtherIDs: Other IDs Non Healthcare 
 * Identifiers</p>
 * 
 * <p>Identifiers used for the focal person by other 
 * organizations are sent in the OtherIDs class. The other 
 * organization can be sent in the E_Organization Entity 
 * Class</p>
 * 
 * <p>Provides the ability to capture additional client 
 * identifiers that are not healthcare specific</p>
 * 
 * <p>PRPA_MT101001CA.OtherIDs: Other IDs Non Healthcare 
 * Identifiers</p>
 * 
 * <p>Identifiers used for the focal person by other 
 * organizations are sent in the OtherIDs class. The other 
 * organization can be sent in the E_Organization Entity 
 * Class</p>
 * 
 * <p>Provides the ability to capture additional client 
 * identifiers that are not healthcare specific</p>
 */
@Hl7PartTypeMapping({"PRPA_MT101001CA.OtherIDs","PRPA_MT101002CA.OtherIDs","PRPA_MT101102CA.OtherIDs","PRPA_MT101104CA.OtherIDs","PRPA_MT101106CA.OtherIDs"})
public class OtherIDsNonHealthcareIdentifiersBean extends MessagePartBean {

    private static final long serialVersionUID = 20121122L;
    private II id = new IIImpl();
    private CV code = new CVImpl();
    private II assigningIdOrganizationId = new IIImpl();
    private ST assigningIdOrganizationName = new STImpl();


    /**
     * <p>NonHealthcareIdentification</p>
     * 
     * <p>NonHealthcare Identification</p>
     * 
     * <p>Other non-healthcare identifiers for the Client (e.g. 
     * Drivers License, RCMP, DND, Social Insurance Number)</p>
     * 
     * <p>Mandatory attribute supports the identification of the 
     * client</p>
     * 
     * <p>NonHealthcare Identification</p>
     * 
     * <p>Other non-healthcare identifiers for the Client (e.g. 
     * Drivers License, RCMP, DND, Social Insurance Number)</p>
     * 
     * <p>Populated attribute supports the identification of the 
     * client</p>
     * 
     * <p>NonHealthcare Identification</p>
     * 
     * <p>Other non-healthcare identifiers for the Client (e.g. 
     * Passport, SIN, DND, DIAND, Drivers License)</p>
     * 
     * <p>Mandatory attribute supports the identification of the 
     * client</p>
     */
    @Hl7XmlMapping({"id"})
    public Identifier getId() {
        return this.id.getValue();
    }

    /**
     * <p>NonHealthcareIdentification</p>
     * 
     * <p>NonHealthcare Identification</p>
     * 
     * <p>Other non-healthcare identifiers for the Client (e.g. 
     * Drivers License, RCMP, DND, Social Insurance Number)</p>
     * 
     * <p>Mandatory attribute supports the identification of the 
     * client</p>
     * 
     * <p>NonHealthcare Identification</p>
     * 
     * <p>Other non-healthcare identifiers for the Client (e.g. 
     * Drivers License, RCMP, DND, Social Insurance Number)</p>
     * 
     * <p>Populated attribute supports the identification of the 
     * client</p>
     * 
     * <p>NonHealthcare Identification</p>
     * 
     * <p>Other non-healthcare identifiers for the Client (e.g. 
     * Passport, SIN, DND, DIAND, Drivers License)</p>
     * 
     * <p>Mandatory attribute supports the identification of the 
     * client</p>
     */
    public void setId(Identifier id) {
        this.id.setValue(id);
    }


    /**
     * <p>NonHealthcareIdentificationCode</p>
     * 
     * <p>NonHealthcare Identification Code</p>
     * 
     * <p>A pan Canadian code further specifying the kind of Role 
     * such as Drivers License, RCMP, DND, Social Insurance 
     * Number</p>
     * 
     * <p>Populated attribute supports the identification of the 
     * client</p>
     */
    @Hl7XmlMapping({"code"})
    public OtherIdentifiersRoleType getCode() {
        return (OtherIdentifiersRoleType) this.code.getValue();
    }

    /**
     * <p>NonHealthcareIdentificationCode</p>
     * 
     * <p>NonHealthcare Identification Code</p>
     * 
     * <p>A pan Canadian code further specifying the kind of Role 
     * such as Drivers License, RCMP, DND, Social Insurance 
     * Number</p>
     * 
     * <p>Populated attribute supports the identification of the 
     * client</p>
     */
    public void setCode(OtherIdentifiersRoleType code) {
        this.code.setValue(code);
    }


    /**
     * <p>NonHealthcareOrganizationIdentifier</p>
     * 
     * <p>NonHealthcare Organization Identifier</p>
     * 
     * <p>Unique identifier for the organization that assigned the 
     * non-healthcare identifier for the client.</p>
     * 
     * <p>Mandatory attribute supports the identification of the 
     * organization assigning the identifier to the client</p>
     */
    @Hl7XmlMapping({"assigningIdOrganization/id"})
    public Identifier getAssigningIdOrganizationId() {
        return this.assigningIdOrganizationId.getValue();
    }

    /**
     * <p>NonHealthcareOrganizationIdentifier</p>
     * 
     * <p>NonHealthcare Organization Identifier</p>
     * 
     * <p>Unique identifier for the organization that assigned the 
     * non-healthcare identifier for the client.</p>
     * 
     * <p>Mandatory attribute supports the identification of the 
     * organization assigning the identifier to the client</p>
     */
    public void setAssigningIdOrganizationId(Identifier assigningIdOrganizationId) {
        this.assigningIdOrganizationId.setValue(assigningIdOrganizationId);
    }


    /**
     * <p>NonHealthcareOrganizationName</p>
     * 
     * <p>NonHealthcare Organization Name</p>
     * 
     * <p>A name for the non-healthcare organization</p>
     * 
     * <p>Populated attribute supports the identification of the 
     * organization assigning the identifier to the client</p>
     */
    @Hl7XmlMapping({"assigningIdOrganization/name"})
    public String getAssigningIdOrganizationName() {
        return this.assigningIdOrganizationName.getValue();
    }

    /**
     * <p>NonHealthcareOrganizationName</p>
     * 
     * <p>NonHealthcare Organization Name</p>
     * 
     * <p>A name for the non-healthcare organization</p>
     * 
     * <p>Populated attribute supports the identification of the 
     * organization assigning the identifier to the client</p>
     */
    public void setAssigningIdOrganizationName(String assigningIdOrganizationName) {
        this.assigningIdOrganizationName.setValue(assigningIdOrganizationName);
    }

}
