/**
 * Copyright 2013 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy$
 * Last modified: $LastChangedDate$
 * Revision:      $LastChangedRevision$
 */
/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.pcs_mr2007_v02_r02.common.coct_mt080100ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.ANY;
import ca.infoway.messagebuilder.datatype.CV;
import ca.infoway.messagebuilder.datatype.IVL;
import ca.infoway.messagebuilder.datatype.TS;
import ca.infoway.messagebuilder.datatype.impl.ANYImpl;
import ca.infoway.messagebuilder.datatype.impl.CVImpl;
import ca.infoway.messagebuilder.datatype.impl.IVLImpl;
import ca.infoway.messagebuilder.datatype.lang.Interval;
import ca.infoway.messagebuilder.model.MessagePartBean;
import ca.infoway.messagebuilder.model.pcs_mr2007_v02_r02.domainvalue.SpecimenObservationCode;
import java.util.Date;



/**
 * <p>Business Name: Specimen Observation</p>
 * 
 * <p>It is sometimes relevant to know certain specimen 
 * characteristics when evaluating a result regarding a 
 * specimen.</p>
 * 
 * <p>One or more observation acts which describe aspects of a 
 * specimen (color, adequacy, etc.)</p>
 */
@Hl7PartTypeMapping({"COCT_MT080100CA.SpecimenObservationEvent"})
public class SpecimenObservationBean extends MessagePartBean {

    private static final long serialVersionUID = 20150903L;
    private CV code = new CVImpl();
    private IVL<TS, Interval<Date>> effectiveTime = new IVLImpl<TS, Interval<Date>>();
    private ANY<Object> value = new ANYImpl<Object>();


    /**
     * <p>Business Name: Specimen Observation Type</p>
     * 
     * <p>Relationship: 
     * COCT_MT080100CA.SpecimenObservationEvent.code</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     * 
     * <p>Type of observation.</p>
     * 
     * <p>Describes the specific observation being 
     * performed/documented.</p>
     */
    @Hl7XmlMapping({"code"})
    public SpecimenObservationCode getCode() {
        return (SpecimenObservationCode) this.code.getValue();
    }

    /**
     * <p>Business Name: Specimen Observation Type</p>
     * 
     * <p>Relationship: 
     * COCT_MT080100CA.SpecimenObservationEvent.code</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     * 
     * <p>Type of observation.</p>
     * 
     * <p>Describes the specific observation being 
     * performed/documented.</p>
     */
    public void setCode(SpecimenObservationCode code) {
        this.code.setValue(code);
    }


    /**
     * <p>Business Name: Specimen Observation Date/Time</p>
     * 
     * <p>Relationship: 
     * COCT_MT080100CA.SpecimenObservationEvent.effectiveTime</p>
     * 
     * <p>Conformance/Cardinality: REQUIRED (0-1)</p>
     * 
     * <p>The date/time when the observation took place. The date 
     * and time of the specimen observation can be relevant in the 
     * result.</p>
     * 
     * <p>When this observation took place (or over what time 
     * interval; for collection).</p>
     */
    @Hl7XmlMapping({"effectiveTime"})
    public Interval<Date> getEffectiveTime() {
        return this.effectiveTime.getValue();
    }

    /**
     * <p>Business Name: Specimen Observation Date/Time</p>
     * 
     * <p>Relationship: 
     * COCT_MT080100CA.SpecimenObservationEvent.effectiveTime</p>
     * 
     * <p>Conformance/Cardinality: REQUIRED (0-1)</p>
     * 
     * <p>The date/time when the observation took place. The date 
     * and time of the specimen observation can be relevant in the 
     * result.</p>
     * 
     * <p>When this observation took place (or over what time 
     * interval; for collection).</p>
     */
    public void setEffectiveTime(Interval<Date> effectiveTime) {
        this.effectiveTime.setValue(effectiveTime);
    }


    /**
     * <p>Business Name: Specimen Observation Value</p>
     * 
     * <p>Relationship: 
     * COCT_MT080100CA.SpecimenObservationEvent.value</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     */
    @Hl7XmlMapping({"value"})
    public Object getValue() {
        return this.value.getValue();
    }

    /**
     * <p>Business Name: Specimen Observation Value</p>
     * 
     * <p>Relationship: 
     * COCT_MT080100CA.SpecimenObservationEvent.value</p>
     * 
     * <p>Conformance/Cardinality: MANDATORY (1)</p>
     */
    public void setValue(Object value) {
        this.value.setValue(value);
    }

}
