/**
 * Copyright 2013 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 15:47:15 -0400 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.nb_pr_cr_lr.lab.polb_mt004200ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.CS;
import ca.infoway.messagebuilder.datatype.impl.CSImpl;
import ca.infoway.messagebuilder.domainvalue.ContextControl;
import ca.infoway.messagebuilder.model.MessagePartBean;
import ca.infoway.messagebuilder.model.nb_pr_cr_lr.common.coct_mt090102ca.HealthcareWorkerBean;
import ca.infoway.messagebuilder.model.nb_pr_cr_lr.common.coct_mt090502ca.HealthcareOrganizationBean;
import ca.infoway.messagebuilder.model.nb_pr_cr_lr.lab.merged.RoleChoice;



/**
 * <p>Business Name: Electronic Result Receiver</p>
 * 
 * <p>Identifies the healthcare providers who are to receive 
 * electronic copies of the result via the JLIS.</p>
 */
@Hl7PartTypeMapping({"POLB_MT004200CA.Receiver"})
public class ElectronicResultReceiverBean extends MessagePartBean {

    private static final long serialVersionUID = 20151013L;
    private CS contextControlCode = new CSImpl();
    private RoleChoice roleChoice;


    /**
     * <p>Relationship: POLB_MT004200CA.Receiver.contextControlCode</p>
     * 
     * <p>Conformance/Cardinality: REQUIRED (0-1)</p>
     */
    @Hl7XmlMapping({"contextControlCode"})
    public ContextControl getContextControlCode() {
        return (ContextControl) this.contextControlCode.getValue();
    }

    /**
     * <p>Relationship: POLB_MT004200CA.Receiver.contextControlCode</p>
     * 
     * <p>Conformance/Cardinality: REQUIRED (0-1)</p>
     */
    public void setContextControlCode(ContextControl contextControlCode) {
        this.contextControlCode.setValue(contextControlCode);
    }


    /**
     * <p>Relationship: POLB_MT004200CA.Receiver.roleChoice</p>
     * 
     * <p>Conformance/Cardinality: REQUIRED (1)</p>
     */
    @Hl7XmlMapping({"roleChoice"})
    public RoleChoice getRoleChoice() {
        return this.roleChoice;
    }

    /**
     * <p>Relationship: POLB_MT004200CA.Receiver.roleChoice</p>
     * 
     * <p>Conformance/Cardinality: REQUIRED (1)</p>
     */
    public void setRoleChoice(RoleChoice roleChoice) {
        this.roleChoice = roleChoice;
    }

    public HealthcareOrganizationBean getRoleChoiceAsAssignedEntity1() {
        return this.roleChoice instanceof HealthcareOrganizationBean ? (HealthcareOrganizationBean) this.roleChoice : null;
    }
    public boolean hasRoleChoiceAsAssignedEntity1() {
        return (this.roleChoice instanceof HealthcareOrganizationBean);
    }

    public HealthcareWorkerBean getRoleChoiceAsAssignedEntity2() {
        return this.roleChoice instanceof HealthcareWorkerBean ? (HealthcareWorkerBean) this.roleChoice : null;
    }
    public boolean hasRoleChoiceAsAssignedEntity2() {
        return (this.roleChoice instanceof HealthcareWorkerBean);
    }

    public ca.infoway.messagebuilder.model.nb_pr_cr_lr.common.coct_mt090508ca.HealthcareOrganizationBean getRoleChoiceAsAssignedEntity3() {
        return this.roleChoice instanceof ca.infoway.messagebuilder.model.nb_pr_cr_lr.common.coct_mt090508ca.HealthcareOrganizationBean ? (ca.infoway.messagebuilder.model.nb_pr_cr_lr.common.coct_mt090508ca.HealthcareOrganizationBean) this.roleChoice : null;
    }
    public boolean hasRoleChoiceAsAssignedEntity3() {
        return (this.roleChoice instanceof ca.infoway.messagebuilder.model.nb_pr_cr_lr.common.coct_mt090508ca.HealthcareOrganizationBean);
    }

}
