/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.interaction;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.model.InteractionBean;
import ca.infoway.messagebuilder.model.common.mcai_mt700210ca.TriggerEventBean;
import ca.infoway.messagebuilder.model.common.mcci_mt000100ca.HL7MessageBean;
import ca.infoway.messagebuilder.model.iehr.repc_mt000017ca.ProfessionalServiceBean;



/**
 * <p>Seeks to add a record of a professional service 
 * (training, counseling, medication reviews, etc.) which has 
 * been delivered to a patient.</p>
 */
@Hl7PartTypeMapping({"REPC_IN000044CA"})
public class RecordPharmacyProfServiceRequestBean extends HL7MessageBean<TriggerEventBean<ProfessionalServiceBean>> implements InteractionBean {

    private static final long serialVersionUID = 20100614L;

}
