/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.merged;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.model.MessagePartBean;



@Hl7PartTypeMapping({"FICR_MT400001CA.DevicePassThru","FICR_MT400003CA.DevicePassThru","FICR_MT400004CA.DevicePassThru","FICR_MT490101CA.DevicePassThru","FICR_MT490102CA.DevicePassThru"})
public class DevicePassThruBean extends MessagePartBean implements SpecialAuthorizationChoice_1Bean, SpecialAuthorizationChoice_2Bean {

    private static final long serialVersionUID = 20100603L;
    private DeviceProductBean directTargetManufacturedProduct;

    @Hl7XmlMapping({"directTarget/manufacturedProduct"})
    public DeviceProductBean getDirectTargetManufacturedProduct() {
        return this.directTargetManufacturedProduct;
    }
    public void setDirectTargetManufacturedProduct(DeviceProductBean directTargetManufacturedProduct) {
        this.directTargetManufacturedProduct = directTargetManufacturedProduct;
    }

}
