/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.merged;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.INT;
import ca.infoway.messagebuilder.datatype.impl.INTImpl;
import ca.infoway.messagebuilder.model.MessagePartBean;



@Hl7PartTypeMapping({"PRPM_MT301010CA.Location","PRPM_MT303010CA.Location"})
public class LocationBean extends MessagePartBean {

    private static final long serialVersionUID = 20100603L;
    private INT orderOfServiceDeliveryLocations = new INTImpl();
    private ServiceDeliveryLocation_3Bean serviceDeliveryLocation;

    @Hl7XmlMapping({"sequenceNumber"})
    public Integer getOrderOfServiceDeliveryLocations() {
        return this.orderOfServiceDeliveryLocations.getValue();
    }
    public void setOrderOfServiceDeliveryLocations(Integer orderOfServiceDeliveryLocations) {
        this.orderOfServiceDeliveryLocations.setValue(orderOfServiceDeliveryLocations);
    }

    @Hl7XmlMapping({"serviceDeliveryLocation"})
    public ServiceDeliveryLocation_3Bean getServiceDeliveryLocation() {
        return this.serviceDeliveryLocation;
    }
    public void setServiceDeliveryLocation(ServiceDeliveryLocation_3Bean serviceDeliveryLocation) {
        this.serviceDeliveryLocation = serviceDeliveryLocation;
    }

}
