/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.merged;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.datatype.II;
import ca.infoway.messagebuilder.datatype.impl.IIImpl;
import ca.infoway.messagebuilder.datatype.lang.Identifier;
import ca.infoway.messagebuilder.model.MessagePartBean;



@Hl7PartTypeMapping({"COCT_MT680000CA.PolicyUnderwriter","FICR_MT500201CA.PolicyUnderwriter","FICR_MT600201CA.PolicyUnderwriter","FICR_MT610201CA.PolicyUnderwriter"})
public class PolicyUnderwriterBean extends MessagePartBean {

    private static final long serialVersionUID = 20110127L;
    private CarrierRoleBean carrierRole;
    private II carrierRoleId = new IIImpl();


    @Hl7XmlMapping({"carrierRole"})
    public CarrierRoleBean getCarrierRole() {
        return this.carrierRole;
    }
    public void setCarrierRole(CarrierRoleBean carrierRole) {
        this.carrierRole = carrierRole;
    }


    /**
     * <p>CarrierRoleId</p>
     * 
     * <p>Carrier Role Id</p>
     */
    @Hl7XmlMapping({"carrierRole/id"})
    public Identifier getCarrierRoleId() {
        return this.carrierRoleId.getValue();
    }
    public void setCarrierRoleId(Identifier carrierRoleId) {
        this.carrierRoleId.setValue(carrierRoleId);
    }

}
