/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.merged;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.model.MessagePartBean;



@Hl7PartTypeMapping({"POIZ_MT030050CA.Reason","POIZ_MT030060CA.Reason","POIZ_MT060150CA.Reason"})
public class ReasonBean extends MessagePartBean {

    private static final long serialVersionUID = 20100603L;
    private ChoiceBean choice;

    @Hl7XmlMapping({"choice"})
    public ChoiceBean getChoice() {
        return this.choice;
    }
    public void setChoice(ChoiceBean choice) {
        this.choice = choice;
    }

    public ImmunizationReasonBean getChoiceAsImmunizationReason() {
        return this.choice instanceof ImmunizationReasonBean ? (ImmunizationReasonBean) this.choice : null;
    }
    public boolean hasChoiceAsImmunizationReason() {
        return (this.choice instanceof ImmunizationReasonBean);
    }

    public NoImmunizationReasonBean getChoiceAsNoImmunizationReason() {
        return this.choice instanceof NoImmunizationReasonBean ? (NoImmunizationReasonBean) this.choice : null;
    }
    public boolean hasChoiceAsNoImmunizationReason() {
        return (this.choice instanceof NoImmunizationReasonBean);
    }

}
