/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.pcs_mr2009_r02_04_02.merged;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;



/**
 * <p>FICR_MT510201CA.InvoiceElementChoice: (no business name)</p>
 * 
 * <p><p>MoodCode: PRP - auth, pre-det, cov ext RQO - 
 * invoice</p></p>
 */
@Hl7PartTypeMapping({"COCT_MT680000CA.InvoiceElementChoice","FICR_MT510201CA.InvoiceElementChoice","FICR_MT610201CA.InvoiceElementChoice"})
public interface InvoiceElementChoice {

}
