/* This class was auto-generated by the message builder generator tools. */
package ca.infoway.messagebuilder.model.claims.ficr_mt510201ca;

import ca.infoway.messagebuilder.annotation.Hl7PartTypeMapping;
import ca.infoway.messagebuilder.annotation.Hl7XmlMapping;
import ca.infoway.messagebuilder.model.merged.AllowableBean;



/**
 * <p>Want sum of all adjudication details (info & non-info) to 
 * equal what was submitted. For example, the reasons why you 
 * refused to pay part of the invoice</p>
 */
@Hl7PartTypeMapping({"FICR_MT510201CA.AdjudicatedInvoiceElementChoice"})
public interface AdjudicatedInvoiceElementChoiceBean {

    public AllowableBean getReference1Allowable();
    public void setReference1Allowable(AllowableBean reference1Allowable);

    public AdjudicationResultBean getOutcomeOfAdjudicationResult();
    public void setOutcomeOfAdjudicationResult(AdjudicationResultBean outcomeOfAdjudicationResult);

}
